services:
  postgres:
    image: postgres:16
    container_name: odinblog-postgres
    restart: always
    environment:
      POSTGRES_USER: viena
      POSTGRES_PASSWORD: odinpassword
      POSTGRES_DB: odin_blog
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./apps/backend/
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://viena:odinpassword@postgres:5432/odin_blog
    ports:
      - "8080:8080"
volumes:
  postgres_data:
